// apps/appgen/apps/we-dev-client/src/components/permissions/ProjectPermissionGuard.tsx
import { ReactNode } from 'react';
import { useProjectPermissions, type RolePermissions } from '@idem/shared-auth-client';
import { authClient } from '../../lib/authClient';

interface ProjectPermissionGuardProps {
  projectId: string;
  permission: keyof RolePermissions;
  children: ReactNode;
  fallback?: ReactNode;
}

export function ProjectPermissionGuard({
  projectId,
  permission,
  children,
  fallback = null,
}: ProjectPermissionGuardProps) {
  const { hasPermission, loading } = useProjectPermissions(authClient, projectId);

  if (loading) {
    return null;
  }

  if (!hasPermission(permission)) {
    return <>{fallback}</>;
  }

  return <>{children}</>;
}

// apps/chart/src/lib/components/permissions/ProjectPermissionGuard.svelte
<script lang="ts">
  import { createProjectPermissionsStore, type RolePermissions } from '@idem/shared-auth-client';
  import { authClient } from '$lib/stores/auth';

  export let projectId: string;
  export let permission: keyof RolePermissions;

  $: permissionsStore = createProjectPermissionsStore(authClient, projectId);
  $: ({ permissions, loading } = $permissionsStore);
  $: hasPermission = permissions ? permissions[permission] : false;
</script>

{#if !loading && hasPermission}
  <slot />
{:else if !loading}
  <slot name="fallback" />
{/if}
