// packages/shared-trusted-by/src/react/trusted-by.tsx
import { useMemo } from 'react';

import { resolvePartners, TRUSTED_BY_ASSETS_BASE_PATH, type ResolvedPartner } from '../partners';

import '../trusted-by.css';

export interface TrustedByProps {
  /** Où l'application sert les logos. Par défaut, le chemin de `sync:trusted-by`. */
  basePath?: string;
  /** Intitulé au-dessus du bandeau. Omis, aucun titre n'est rendu. */
  label?: string;
  /** Classes ajoutées au conteneur, pour l'intégration dans la page hôte. */
  className?: string;
}

/**
 * Bandeau défilant « Ils nous font confiance », partagé par les applications
 * React d'Idem (iCode / AppGen).
 *
 * Même données, même feuille de style que la version Angular : seul le rendu
 * change, parce que le framework change. Les logos sont servis par
 * l'application hôte, où `npm run sync:trusted-by` les dépose.
 */
export function TrustedBy({ basePath, label, className }: TrustedByProps) {
  const partners = useMemo<ResolvedPartner[]>(
    () => resolvePartners(basePath ?? TRUSTED_BY_ASSETS_BASE_PATH),
    [basePath]
  );

  return (
    <div className={className ? `idem-trusted-by ${className}` : 'idem-trusted-by'}>
      {label ? <p className="idem-trusted-by__label">{label}</p> : null}
      <div className="idem-trusted-by__viewport">
        <div className="idem-trusted-by__track">
          {partners.map((partner) => (
            <a
              key={partner.name}
              className="idem-trusted-by__link"
              href={partner.url}
              title={partner.name}
              target="_blank"
              rel="noopener noreferrer"
            >
              <img className="idem-trusted-by__logo" src={partner.logoUrl} alt={partner.name} />
            </a>
          ))}
        </div>
        {/* Copie décorative : elle assure la boucle, pas le contenu. */}
        <div className="idem-trusted-by__track" aria-hidden="true">
          {partners.map((partner) => (
            <span key={partner.name} className="idem-trusted-by__link">
              <img className="idem-trusted-by__logo" src={partner.logoUrl} alt="" />
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}

export default TrustedBy;

// packages/shared-trusted-by/src/angular/trusted-by.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

import { resolvePartners, TRUSTED_BY_ASSETS_BASE_PATH, type ResolvedPartner } from '../partners';

/**
 * Bandeau défilant « Ils nous font confiance », partagé par les applications
 * Angular d'Idem (landing, iDeploy, …).
 *
 * Les logos sont servis par l'application hôte : `npm run sync:trusted-by` les
 * dépose dans son dossier `public/`. Si une application les monte ailleurs,
 * elle le dit via `basePath`.
 *
 * @example
 * ```html
 * <idem-trusted-by label="Ils nous font confiance" />
 * ```
 */
@Component({
  selector: 'idem-trusted-by',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="idem-trusted-by">
      @if (label(); as heading) {
        <p class="idem-trusted-by__label">{{ heading }}</p>
      }
      <div class="idem-trusted-by__viewport">
        <div class="idem-trusted-by__track">
          @for (partner of partners(); track partner.name) {
            <a
              class="idem-trusted-by__link"
              [href]="partner.url"
              [title]="partner.name"
              target="_blank"
              rel="noopener noreferrer"
            >
              <img class="idem-trusted-by__logo" [src]="partner.logoUrl" [alt]="partner.name" />
            </a>
          }
        </div>
        <!-- Copie décorative : elle assure la boucle, pas le contenu. -->
        <div class="idem-trusted-by__track" aria-hidden="true">
          @for (partner of partners(); track partner.name) {
            <span class="idem-trusted-by__link">
              <img class="idem-trusted-by__logo" [src]="partner.logoUrl" alt="" />
            </span>
          }
        </div>
      </div>
    </div>
  `,
  styleUrls: ['../trusted-by.css'],
})
export class TrustedByComponent {
  /** Où l'application sert les logos. Par défaut, le chemin de `sync:trusted-by`. */
  readonly basePath = input<string>(TRUSTED_BY_ASSETS_BASE_PATH);

  /** Intitulé au-dessus du bandeau. Omis, aucun titre n'est rendu. */
  readonly label = input<string | null>(null);

  protected readonly partners = computed<ResolvedPartner[]>(() => resolvePartners(this.basePath()));
}
