// packages/shared-auth-client/examples/react-example.tsx
/**
 * Exemple d'intégration React pour appgen
 *
 * Installation:
 * npm install @idem/shared-auth-client
 */

import React, { createContext, useContext, useMemo } from 'react';
import { AuthClient, useAuth, useProjectPermissions } from '@idem/shared-auth-client';

// 1. Créer le contexte AuthClient
const AuthClientContext = createContext<AuthClient | null>(null);

// 2. Provider pour l'application
export function AuthClientProvider({ children }: { children: React.ReactNode }) {
  const authClient = useMemo(() => {
    return new AuthClient({
      apiBaseUrl: import.meta.env.VITE_API_URL || 'http://localhost:3001',
      // Session : cookie httpOnly `session` posé par l'API IDEM, envoyé automatiquement.
    });
  }, []);

  return <AuthClientContext.Provider value={authClient}>{children}</AuthClientContext.Provider>;
}

// 3. Hook pour accéder au client
export function useAuthClient() {
  const client = useContext(AuthClientContext);
  if (!client) {
    throw new Error('useAuthClient must be used within AuthClientProvider');
  }
  return client;
}

// 4. Composant de gestion des équipes
export function TeamManagement() {
  const authClient = useAuthClient();
  const { teams, loading, error, createTeam, inviteUser } = useAuth(authClient);
  const [showCreateModal, setShowCreateModal] = React.useState(false);
  const [showInviteModal, setShowInviteModal] = React.useState<string | null>(null);

  if (loading) {
    return <div className="loading">Loading teams...</div>;
  }

  if (error) {
    return <div className="error">Error: {error.message}</div>;
  }

  return (
    <div className="team-management">
      <div className="header">
        <h1>My Teams</h1>
        <button onClick={() => setShowCreateModal(true)}>Create Team</button>
      </div>

      <div className="teams-grid">
        {teams.map((team) => (
          <div key={team.id} className="team-card">
            <h2>{team.name}</h2>
            <p>{team.description}</p>
            <p className="members-count">
              {team.members.length} member{team.members.length !== 1 ? 's' : ''}
            </p>

            <div className="members-list">
              {team.members.map((member) => (
                <div key={member.userId} className="member">
                  <span>{member.displayName}</span>
                  <span className="role">{member.role}</span>
                </div>
              ))}
            </div>

            <button onClick={() => setShowInviteModal(team.id!)}>Invite User</button>
          </div>
        ))}
      </div>

      {showCreateModal && (
        <CreateTeamModal onClose={() => setShowCreateModal(false)} onCreate={createTeam} />
      )}

      {showInviteModal && (
        <InviteUserModal
          teamId={showInviteModal}
          onClose={() => setShowInviteModal(null)}
          onInvite={inviteUser}
        />
      )}
    </div>
  );
}

// 5. Composant avec vérification de permissions
export function ProjectActions({ projectId }: { projectId: string }) {
  const authClient = useAuthClient();
  const { permissions, loading, hasPermission } = useProjectPermissions(authClient, projectId);

  if (loading) {
    return <div>Loading permissions...</div>;
  }

  return (
    <div className="project-actions">
      {hasPermission('canEdit') && (
        <button onClick={() => console.log('Edit project')}>Edit Project</button>
      )}

      {hasPermission('canDeploy') && (
        <button onClick={() => console.log('Deploy project')}>Deploy</button>
      )}

      {hasPermission('canDelete') && (
        <button onClick={() => console.log('Delete project')} className="danger">
          Delete Project
        </button>
      )}

      {hasPermission('canManageTeams') && (
        <button onClick={() => console.log('Manage teams')}>Manage Teams</button>
      )}

      {!permissions && <div className="no-access">You don't have access to this project</div>}
    </div>
  );
}

// 6. Modals (exemples simplifiés)
function CreateTeamModal({ onClose, onCreate }: any) {
  const [name, setName] = React.useState('');
  const [description, setDescription] = React.useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    await onCreate(name, description);
    onClose();
  };

  return (
    <div className="modal">
      <form onSubmit={handleSubmit}>
        <h2>Create Team</h2>
        <input
          type="text"
          placeholder="Team name"
          value={name}
          onChange={(e) => setName(e.target.value)}
          required
        />
        <textarea
          placeholder="Description"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
        />
        <div className="actions">
          <button type="button" onClick={onClose}>
            Cancel
          </button>
          <button type="submit">Create</button>
        </div>
      </form>
    </div>
  );
}

function InviteUserModal({ teamId, onClose, onInvite }: any) {
  const [email, setEmail] = React.useState('');
  const [displayName, setDisplayName] = React.useState('');
  const [role, setRole] = React.useState('member');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    await onInvite(email, displayName, teamId, role);
    alert('Invitation sent!');
    onClose();
  };

  return (
    <div className="modal">
      <form onSubmit={handleSubmit}>
        <h2>Invite User</h2>
        <input
          type="email"
          placeholder="Email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          required
        />
        <input
          type="text"
          placeholder="Display Name"
          value={displayName}
          onChange={(e) => setDisplayName(e.target.value)}
          required
        />
        <select value={role} onChange={(e) => setRole(e.target.value)}>
          <option value="member">Member</option>
          <option value="admin">Admin</option>
          <option value="viewer">Viewer</option>
        </select>
        <div className="actions">
          <button type="button" onClick={onClose}>
            Cancel
          </button>
          <button type="submit">Send Invitation</button>
        </div>
      </form>
    </div>
  );
}

// 7. Utilisation dans App.tsx
export function App() {
  return (
    <AuthClientProvider>
      <div className="app">
        <TeamManagement />
        {/* Autres composants */}
      </div>
    </AuthClientProvider>
  );
}

// packages/shared-auth-client/examples/svelte-example.svelte
<!--
  Exemple d'intégration Svelte pour chart
  
  Installation:
  npm install @idem/shared-auth-client
-->

<script lang="ts">
  /**
   * 1. Créer le store dans un fichier séparé (stores/auth.ts)
   */
  
  // stores/auth.ts
  import { AuthClient } from '@idem/shared-auth-client';
  import { createAuthStore, createProjectPermissionsStore } from '@idem/shared-auth-client';

  const authClient = new AuthClient({
    apiBaseUrl: import.meta.env.VITE_API_URL || 'http://localhost:3001',
    // Session : cookie httpOnly `session` posé par l'API IDEM, envoyé automatiquement.
  });

  export const authStore = createAuthStore(authClient);
  export { authClient };
</script>

<!-- 2. Composant de gestion des équipes -->
<script lang="ts">
  import { authStore, authClient } from './stores/auth';
  import { createProjectPermissionsStore } from '@idem/shared-auth-client';
  
  let showCreateModal = false;
  let showInviteModal: string | null = null;
  
  $: ({ teams, loading, error } = $authStore);
  
  async function handleCreateTeam(name: string, description: string) {
    await authStore.createTeam(name, description);
    showCreateModal = false;
  }
  
  async function handleInviteUser(email: string, displayName: string, teamId: string, role: string) {
    await authStore.inviteUser(email, displayName, teamId, role);
    showInviteModal = null;
  }
</script>

<div class="team-management">
  <div class="header">
    <h1>My Teams</h1>
    <button on:click={() => showCreateModal = true}>
      Create Team
    </button>
  </div>

  {#if loading}
    <div class="loading">Loading teams...</div>
  {:else if error}
    <div class="error">Error: {error.message}</div>
  {:else}
    <div class="teams-grid">
      {#each teams as team (team.id)}
        <div class="team-card">
          <h2>{team.name}</h2>
          <p>{team.description || ''}</p>
          <p class="members-count">
            {team.members.length} member{team.members.length !== 1 ? 's' : ''}
          </p>
          
          <div class="members-list">
            {#each team.members as member (member.userId)}
              <div class="member">
                <span>{member.displayName}</span>
                <span class="role">{member.role}</span>
              </div>
            {/each}
          </div>

          <button on:click={() => showInviteModal = team.id}>
            Invite User
          </button>
        </div>
      {/each}
    </div>
  {/if}

  {#if showCreateModal}
    <CreateTeamModal
      on:close={() => showCreateModal = false}
      on:create={(e) => handleCreateTeam(e.detail.name, e.detail.description)}
    />
  {/if}

  {#if showInviteModal}
    <InviteUserModal
      teamId={showInviteModal}
      on:close={() => showInviteModal = null}
      on:invite={(e) => handleInviteUser(
        e.detail.email,
        e.detail.displayName,
        showInviteModal,
        e.detail.role
      )}
    />
  {/if}
</div>

<!-- 3. Composant avec vérification de permissions -->
<script lang="ts">
  export let projectId: string;
  
  $: permissionsStore = createProjectPermissionsStore(authClient, projectId);
  $: ({ permissions, loading: permLoading } = $permissionsStore);
</script>

<div class="project-actions">
  {#if permLoading}
    <div>Loading permissions...</div>
  {:else if permissions}
    {#if permissions.canEdit}
      <button on:click={() => console.log('Edit project')}>
        Edit Project
      </button>
    {/if}

    {#if permissions.canDeploy}
      <button on:click={() => console.log('Deploy project')}>
        Deploy
      </button>
    {/if}

    {#if permissions.canDelete}
      <button on:click={() => console.log('Delete project')} class="danger">
        Delete Project
      </button>
    {/if}

    {#if permissions.canManageTeams}
      <button on:click={() => console.log('Manage teams')}>
        Manage Teams
      </button>
    {/if}
  {:else}
    <div class="no-access">
      You don't have access to this project
    </div>
  {/if}
</div>

<style>
  .team-management {
    padding: 2rem;
  }

  .header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 2rem;
  }

  .teams-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: 1.5rem;
  }

  .team-card {
    border: 1px solid #e0e0e0;
    border-radius: 8px;
    padding: 1.5rem;
    background: white;
  }

  .team-card h2 {
    margin: 0 0 0.5rem 0;
    font-size: 1.25rem;
  }

  .members-count {
    color: #666;
    font-size: 0.875rem;
    margin: 0.5rem 0;
  }

  .members-list {
    margin: 1rem 0;
  }

  .member {
    display: flex;
    justify-content: space-between;
    padding: 0.5rem 0;
    border-bottom: 1px solid #f0f0f0;
  }

  .role {
    color: #666;
    font-size: 0.875rem;
    text-transform: capitalize;
  }

  button {
    padding: 0.5rem 1rem;
    border: none;
    border-radius: 4px;
    background: #007bff;
    color: white;
    cursor: pointer;
  }

  button:hover {
    background: #0056b3;
  }

  button.danger {
    background: #dc3545;
  }

  button.danger:hover {
    background: #c82333;
  }

  .loading, .error, .no-access {
    padding: 2rem;
    text-align: center;
  }

  .error {
    color: #dc3545;
  }
</style>
